DROP TABLE IF EXISTS calandar;

CREATE TABLE calandar(
    id INTEGER AUTO_INCREMENT PRIMARY KEY
    event VARCHAR(50) NOT NULL,
    host VARCHAR(50),
    event_date MONTHNAME DAYOFMONTH DAYOFYEAR()  
);